### ISSUE TITLE
Seg fault caused by invalid track state at calo access

### ISSUE THREAD

**Issue by rete** [iLCSoft/DDMarlinPandora#15]
- OS version: SLC6
 - Compiler version: GCC 4.9
 - Package version: afs ILCSoft version HEAD-2017-10-12, DDMarlinPandora commit 2da2612de752c428f326efe8428364811ee1201d
 - Reproduced by: Running the ILDConfig chain on bbuds 3 events
 - Goal: Fix a seg fault related to track state at calorimeter

By running the ILDConfig example with the 3 event example, simulation runs well but reconstruction fails on first event. ROOt gives this stack : 

```shell
===========================================================
#5  0x00007feb6523dbd3 in MarlinTrk::MarlinDDKalTestTrack::findIntersection(DDVMeasLayer const&, TKalTrackSite const&, dd4hep::rec::Vector3D&, double&, int&, int) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/MarlinTrk/HEAD/src/MarlinDDKalTestTrack.cc:1498
#6  0x00007feb6523dedd in MarlinTrk::MarlinDDKalTestTrack::findIntersection(std::vector<DDVMeasLayer const*, std::allocator<DDVMeasLayer const*> >&, TKalTrackSite const&, dd4hep::rec::Vector3D&, int&, DDVMeasLayer const*&, int) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/MarlinTrk/HEAD/src/MarlinDDKalTestTrack.cc:1558
#7  0x00007feb6523d8b3 in MarlinTrk::MarlinDDKalTestTrack::intersectionWithLayer(int, TKalTrackSite const&, dd4hep::rec::Vector3D&, int&, DDVMeasLayer const*&, int) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/MarlinTrk/HEAD/src/MarlinDDKalTestTrack.cc:1463
#8  0x00007feb6523ce67 in MarlinTrk::MarlinDDKalTestTrack::propagateToLayer(int, TKalTrackSite const&, IMPL::TrackStateImpl&, double&, int&, int&, int) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/MarlinTrk/HEAD/src/MarlinDDKalTestTrack.cc:1313
#9  0x00007feb6523cd3d in MarlinTrk::MarlinDDKalTestTrack::propagateToLayer(int, IMPL::TrackStateImpl&, double&, int&, int&, int) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/MarlinTrk/HEAD/src/MarlinDDKalTestTrack.cc:1288
#10 0x00007feb667e22ef in DDTrackCreatorBase::GetTrackStatesAtCalo(EVENT::Track*, lc_content::LCTrackParameters&) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/DDMarlinPandora/HEAD/src/DDTrackCreatorBase.cc:447
#11 0x00007feb667f4440 in DDTrackCreatorILD::CreateTracks(EVENT::LCEvent*) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/DDMarlinPandora/HEAD/src/DDTrackCreatorILD.cc:254
#12 0x00007feb667ca7a7 in DDPandoraPFANewProcessor::processEvent(EVENT::LCEvent*) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/DDMarlinPandora/HEAD/src/DDPandoraPFANewProcessor.cc:213
#13 0x00007feb70c67424 in marlin::ProcessorMgr::processEvent(EVENT::LCEvent*) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/Marlin/HEAD/source/src/ProcessorMgr.cc:470
#14 0x00007feb706c766c in SIO::SIOReader::readStream(int) () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/lcio/HEAD/src/cpp/src/SIO/SIOReader.cc:732
#15 0x00007feb706c73b7 in SIO::SIOReader::readStream() () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/lcio/HEAD/src/cpp/src/SIO/SIOReader.cc:660
#16 0x000000000041a34b in main () at /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-10-12/Marlin/HEAD/source/src/Marlin.cc:509
===========================================================
```

**Comment by andresailer** [comment]
Since when is this happening?
Maybe you could make an automatic test like it has been proposed here: ILCSoft/ILDConfig#2

**Comment by rete** [comment]
The problem couldn't have been reproduced with the version v01-19-05-pre01 installed in afs and with the head version of ILDConfig. Something went wrong with my steering files maybe. I close the issue ...
